# Generated by Django 3.0 on 2021-12-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.IntegerField()),
                ('group_name', models.CharField(max_length=50)),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LopSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('last_month', models.DateTimeField(blank=True, null=True)),
                ('this_month', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('point_amt', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=7, null=True)),
                ('category', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'db_table': 'lop_sample',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LopSample2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('last_month', models.DateTimeField(blank=True, null=True)),
                ('this_month', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('point_amt', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=7, null=True)),
                ('category', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'db_table': 'lop_sample_2',
                'managed': False,
            },
        ),
    ]
